<?php

namespace Plugin\PluginHoliday\Repository;

use Doctrine\Persistence\ManagerRegistry;
use Eccube\Repository\AbstractRepository;
use Plugin\PluginHoliday\Entity\Holiday;

/**
 * ConfigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HolidayRepository extends AbstractRepository
{
    /**
     * ConfigRepository constructor.
     *
     * @param ManagerRegistry $registry
     */
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, Holiday::class);
    }

    /**
     * @param int $id
     *
     * @return Holiday
     *
     * @throws \Exception
     */
    public function get($id = 1)
    {
        $Holiday = $this->find($id);

        if (null === $Holiday) {
            throw new \Exception('Config not found. id = '.$id);
        }

        return $Holiday;
    }

    /**
     * Tạo buider tìm kiếm 
     */
    public function getQueryBuilderBySearchData( array $searchData = [] )
    {
        $qb = $this->createQueryBuilder('h')
        ->orderBy('h.id', 'ASC');

        //search by name
        if (!empty($searchData['name'])) {
            $qb->andWhere('h.name LIKE :name')
            ->setParameter('name', '%'.$searchData['name'].'%');
        }

        //search by message
        if (!empty($searchData['holiday_message'])) {
            $qb->andWhere('h.holiday_message LIKE :holiday_message')
            ->setParameter('holiday_message', '%'.$searchData['holiday_message'].'%');
        }

        //search by date
        if (!empty($searchData['holiday_date']) && $searchData['holiday_date'] instanceof \DateTime) {
            $dateStr = $searchData['holiday_date']->format('m-d');
            $qb->andWhere('h.holiday_date = :holiday_date')
            ->setParameter('holiday_date', $dateStr);
        }
        return $qb;
    }
}
